### ISSUE TITLE
Open results in a new tab/window

### ISSUE THREAD

**Issue by certainlyakey** [am-impact/amcommand#28]
It would be really nice if we could open the new page in a new tab, for example by hitting Cmd+Enter instead of Enter. Often I just forget to create an entry to which the current one should be related, open amcommand and hit "create new", but I still want to keep the previous page open to make the relation after that entry was created.

**Comment by hubertprein** [comment]
This is already available! Simply hit the keyboard shortcut you just mentioned.

**Comment by certainlyakey** [comment]
Thanks @hubertprein!
