### ISSUE TITLE
RC11 Bug

### ISSUE THREAD

**Issue by ghost** [am-impact/amcommand#35]
Updated to 3.0.0-RC11 and the command palette stopped working.
When I click on the link in the admin sidebar nav, I get the following error page:
https://cl.ly/433K3P1d432z

Was working fine in RC10.1

**Comment by hubertprein** [comment]
Works perfectly fine for me with the 3.0.0-RC11 version. Any specific OS or browser?

**Comment by hubertprein** [comment]
You probably had different plugins that use / or have custom Javascript that had an error while the command palette also tried to initiate its Javascript. Can't reproduce.
