### ISSUE TITLE
Requirements could not be resolved to an installable set of packages (Craft 3)

### ISSUE THREAD

**Issue by j-greig** [am-impact/amcommand#37]
I installed the plugin on a staging server, then got this error when running `composer update` locally. 

Looks like the package name needs to be changed to `am-impact/amcommand`?

`The requested package amimpact/command-palette could not be found in any version, there may be a typo in the package name.`

**Comment by hubertprein** [comment]
Hmm... Haven't run into this issue yet. Could be that's the case.. let me get back to you on that.

**Comment by hechtron** [comment]
Hi, I've continually had this issue with Craft 3. It seems if installed via composer I invariably get this issue, whereas via the Plugin Store I typically don't. Really love the plugin, so very much hoping you can resolve this.

**Comment by hubertprein** [comment]
Changed the package name so it shouldn't happen anymore. Couldn't test the plugin store way yet, since there's an error in it.
